- hosts: 10Kservers
  tasks:
    - name: Shutdown GPFS node
      command: mmshutdown
    - name: Stop multipathd
      service: name=multipathd state=stopped
    - name: Flash multipath
      command: multipath -F
    - name: Start ddn-ibsrp
      service: name=ddn-ibsrp state=restarted
    - name: Start multipathd
      service: name=multipathd state=started
